= Git Gud Speaker Outline - Day 2
:hardbreaks:

== Overview
The goal of this presentation is to give a broader understanding of how git works as a distributed
version control system, especially with respect to remotes and their importance. Again, this presentation
is geared around presenting the theory, and practical application questions should wait until the 
end of the presentation.

=== Day 1 Review questions
* What is in a commit?
** author, date, message, hash, diff
* What is stored when you create a commit?
** pointer to parent, and delta of change
* How do you create a new branch?
* What is HEAD, and what does it represent?
* What is a *detached HEAD* state, and how do you fix it?
** git branch _<branch_name>_, git checkout _<branch_name>_
** git checkout -b _<branch_name>_
* What does *git checkout HEAD~2* do?
* Walk me through the process of merging _branch_a_ into _branch_b_
* If you have two commits with identical file changes, message, author, and date, are they the same commit?
** No, hash will differ

== Understand Your Audience
* Has anyone here worked with remotes before?
** ^^ rhetorical question, *everyone* that has worked with git has used remotes

== Remotes
* *Q*: Can anyone tell me what a remote is?
* *A*: A pointer to a server that also hosts the repository. Mostly just contains a server url and name
* *Q*: Aside from the url, are there any differences between the contents of the remote vs the contents on your machine?
* *A*: The server contains exactly the same content as your local copy of the repository, with a handful of exceptions you specify in the _.gitignore_
* git is a _Distributed Version Control System_ or DVCS, so it mirrors all contents of the remote to your computer
* super handy since if you lose git for some reason, you can still do everything locally

== Interacting with Remotes
* Adding a remote
** git remote add origin <url>
* Typically, the primary source repository for your codebase is referred to as _origin_
* other remote names will vary
** typically adding backslashes into 
